{% set name = "smbprotocol" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eac7ec6d52191289e028cc9d72cf29c76363c34634fcd1c0509a8e85af978c67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - cryptography >=2.0
    - pyspnego
  run_constrained:
    - python-gssapi >=1.4.1

test:
  imports:
    - smbprotocol

about:
  home: https://github.com/jborean93/smbprotocol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interact with a server using the SMB 2/3 Protocol
  doc_url: https://github.com/jborean93/smbprotocol
  dev_url: https://github.com/jborean93/smbprotocol

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
