{% set name = "smbprotocol" %}
{% set version = "1.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c892f4c22ab147d0576a3a8d34279831b26ab4695b7df911a334bc41f6d652a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0.0
  run:
    - python >={{ python_min }}
    - cryptography >=2.0
    - pyspnego

test:
  requires:
    - python {{ python_min }}
  imports:
    - smbprotocol

about:
  home: https://github.com/jborean93/smbprotocol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interact with a server using the SMB 2/3 Protocol
  doc_url: https://github.com/jborean93/smbprotocol
  dev_url: https://github.com/jborean93/smbprotocol

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
