{% set name = "smbprotocol" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4918ba10a0b0b344308e7a043c1c6741bf7282c3937059a5852de702d3b684da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - cryptography >=2.0
    - pyspnego

test:
  imports:
    - smbprotocol

about:
  home: https://github.com/jborean93/smbprotocol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Interact with a server using the SMB 2/3 Protocol
  doc_url: https://github.com/jborean93/smbprotocol
  dev_url: https://github.com/jborean93/smbprotocol

extra:
  recipe-maintainers:
    - krisevans
    - dhirschfeld
